server:
  port: 8080
  context-path: /
  session:
    timeout: 3600

spring:
  datasource:
    url: jdbc:mysql://172.17.21.59:3306/activiti
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      min-idle: 2
      max-idle: 10
      max-active: 20
      max-wait: 200
      test-on-borrow: true
  session:
      store-type: redis
      redis:
        namespace: ucas:rdpdemo
  aop:
    auto: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/pages/
  redis:
    host: 172.17.21.59
    password: 123456
#    cluster:
#       nodes:
#              - 172.17.21.59:7003
#              - 172.17.21.59:7004
#              - 172.17.21.59:7005
#              - 172.17.21.63:7009
#              - 172.17.21.63:7011
#              - 172.17.21.63:7010

  data:
    mongodb:
      host: 172.17.21.59
      port: 27017
      dbname: client
      database: client
  activiti:
    checkProcessDefinitions: false

mybatis:
  mapper-locations: classpath:sql/mapper/*.xml

#是否启动quartz任务扫描器
quartz:
  scan: false

#认证中心交互参数
ucas:
  core:
    name: test
    hosturl: http://172.17.21.59:8090/ucas_core
    client_id: "00000000000000000000000000000001"
    client_secret: "000000000000000001"
    oauth2Url: oauth/authorize?response_type=code&scope=client_userinfo&state=123&client_id=
    localLoginUrl: login
    getTokenUrl: oauth/accessToken
    logout:  oauth/logout?response_type=code&scope=client_userinfo&state=123&client_id=
    mainIndex: index
    scope: client_userinfo
    grant_type: authorization_code


# 登录参数管理
loginParam:
  # session管理方式：header/cookies
  sessionType: cookies
  # 是否使用第三方用户登录
  oauthUser: false
  # 是否有本地用户
  hasLocalUser: true
  # 图形验证码开启
  captcha: false
  # 图形验证码有效时间（秒）
  captchaExpire: 120

# 用户参数
user:
  # 初始密码
  initPwd: ucsmy123456

# 序列号生成器配置，格式：4位前缀 + 8位日期 + 6位流水号，限制长度必须为18位，目前长度不支持配置
serialNumber:
  # 是否开启:true;false
  open: true
  # 生成模式：db；redis; default(乱序模式)
  mode: redis
  # 序列号默认前缀
  prefix: 1000
  # 序列号备用前缀，当出现重复主键时使用备用序列号生成器生成
  backupPrefix: 9900
  # 序列号编号格式
  numberPattern: "000000"
  # 序列号日期格式
  datePattern: yyMMddHH
  # db模式线程最大等待时间，毫秒
  waitTime: 10000
  # 序列号起始基数
  startNum: 1
