-- 导出 ucas_center 的数据库结构
CREATE DATABASE IF NOT EXISTS `ucas_center` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `ucas_center`;

/*
DROP TABLE UCAS_USER_INFO;



DROP TABLE UCAS_CLIENT_RESGR_REL;



DROP TABLE UCAS_USER_RES_REL;



DROP TABLE UCAS_ACCCLI_GROUP_REL;



DROP TABLE UCAS_CLIENT_TOKEN;



DROP TABLE UCAS_USER_CLIENT_REL;



DROP TABLE UCAS_USER_ACCOUNT;



DROP TABLE UCAS_ACCOUNT_GROUP;



DROP TABLE UCAS_CALL_TICKET;



DROP TABLE UCAS_CLIENT_RESOURCE;



DROP TABLE UCAS_RESOURCE_GROUP;



DROP TABLE UCAS_TOKEN_STRATEGY;



DROP TABLE UCAS_CLIENT_INFO;



DROP TABLE UCAS_CLIENT_GROUP;

*/

CREATE TABLE UCAS_ACCCLI_GROUP_REL
(
	UUID                 VARCHAR(32) NOT NULL,
	ACCG_UUID            VARCHAR(32) NOT NULL,
	CLIG_UUID            VARCHAR(32) NOT NULL
);



ALTER TABLE UCAS_ACCCLI_GROUP_REL
ADD PRIMARY KEY (UUID);



CREATE TABLE UCAS_ACCOUNT_GROUP
(
	ACCG_UUID            VARCHAR(32) NOT NULL,
	GROUP_NAME           VARCHAR(50) NULL,
	DESC_RIBE            VARCHAR(200) NULL
);



ALTER TABLE UCAS_ACCOUNT_GROUP
ADD PRIMARY KEY (ACCG_UUID);



CREATE TABLE UCAS_CALL_TICKET
(
	CALL_TICKET           VARCHAR(32) NOT NULL,
	CLIENT_ID            VARCHAR(32) NOT NULL,
	RES_UUID             TEXT NOT NULL,
	MAX_TIMES            INTEGER NULL,
	CUR_TIMES            INTEGER NULL,
	CREATE_DATE          DATETIME NULL,
	INVALID_DATE         DATETIME NULL,
	SCOPE                VARCHAR(2000) NULL
);



ALTER TABLE UCAS_CALL_TICKET
ADD PRIMARY KEY (CALL_TICKE);



CREATE TABLE UCAS_CLIENT_GROUP
(
	CLIG_UUID            VARCHAR(32) NOT NULL,
	GROUP_NAME           VARCHAR(50) NULL,
	DESC_RIBE            VARCHAR(200) NULL,
	IS_SSO               CHAR(1) NULL
);



ALTER TABLE UCAS_CLIENT_GROUP
ADD PRIMARY KEY (CLIG_UUID);



CREATE TABLE UCAS_CLIENT_INFO
(
	CLIENT_ID            VARCHAR(32) NOT NULL,
	CLIG_UUID            VARCHAR(32) NOT NULL,
	CLIENT_SECRET        VARCHAR(18) NULL,
	CLIENT_NAME          VARCHAR(100) NULL,
	DESC_RIBE            VARCHAR(200) NULL,
	GRANT_TYPE           VARCHAR(100) NULL,
	CLIENT_URL           VARCHAR(200) NULL,
	STATUS               CHAR(1) NULL,
	CREATE_DATE          DATETIME NULL,
	MODIFY_DATE          DATETIME NULL
);



ALTER TABLE UCAS_CLIENT_INFO
ADD PRIMARY KEY (CLIENT_ID);



CREATE TABLE UCAS_CLIENT_RESGR_REL
(
	UUID                 VARCHAR(32) NOT NULL,
	CLIENT_ID            VARCHAR(32) NOT NULL,
	RES_GROUP_UUID       VARCHAR(32) NOT NULL,
	MAX_TIMES            INTEGER NULL,
	EXPIRY_DATE          INTEGER NULL,
	MODIFY_DATE          DATETIME NULL,
	CREATE_DATE          DATETIME NULL
);



ALTER TABLE UCAS_CLIENT_RESGR_REL
ADD PRIMARY KEY (UUID);



CREATE TABLE UCAS_CLIENT_RESOURCE
(
	RES_UUID             VARCHAR(32) NOT NULL,
	RES_GROUP_UUID       VARCHAR(32) NOT NULL,
	RES_URI              VARCHAR(200) NULL,
	DESC_RIBE            VARCHAR(200) NULL,
	IS_PRIVACY           CHAR(1) NULL,
	IS_DEFAULT           CHAR(1) NULL,
	CREATE_DATE          DATETIME NULL,
	MODIFY_DATE          DATETIME NULL,
	STATUS               CHAR(1) NULL
);



ALTER TABLE UCAS_CLIENT_RESOURCE
ADD PRIMARY KEY (RES_UUID);



CREATE TABLE UCAS_CLIENT_TOKEN
(
	UUID                 VARCHAR(32) NOT NULL,
	CLIENT_ID            VARCHAR(32) NOT NULL,
	OPEN_ID              VARCHAR(32) NULL,
	CODE                 CHAR(18) NULL,
	ACCESS_TOKEN         VARCHAR(32) NULL,
	MAX_TIMES            INTEGER NULL,
	CUR_TIMES            INTEGER NULL,
	CREATE_DATE          DATETIME NULL,
	INVALID_DATE         DATETIME NULL,
	REFRESH_TOKEN        VARCHAR(32) NULL,
	REFRESH_TOKEN_DATE   DATETIME NULL,
	SCOPE                VARCHAR(2000) NULL
);



ALTER TABLE UCAS_CLIENT_TOKEN
ADD PRIMARY KEY (UUID);



CREATE TABLE UCAS_RESOURCE_GROUP
(
	RES_GROUP_UUID       VARCHAR(32) NOT NULL,
	CLIENT_ID            VARCHAR(32) NOT NULL,
	GROUP_NAME           VARCHAR(50) NULL,
	DESC_RIBE            VARCHAR(200) NULL
);



ALTER TABLE UCAS_RESOURCE_GROUP
ADD PRIMARY KEY (RES_GROUP_UUID);



CREATE TABLE UCAS_TOKEN_STRATEGY
(
	UUID                 VARCHAR(32) NOT NULL,
	CLIENT_ID            VARCHAR(32) NOT NULL,
	MAX_TIMES            INTEGER NULL,
	EXPIRY_DATE          INTEGER NOT NULL,
	REFRESH_EXPIRY_DATE  INTEGER NOT NULL,
	STATUS               CHAR(1) NOT NULL,
	CREATE_DATE          DATETIME NOT NULL
);



ALTER TABLE UCAS_TOKEN_STRATEGY
ADD PRIMARY KEY (UUID);



CREATE TABLE UCAS_USER_ACCOUNT
(
	ACC_UUID             VARCHAR(32) NOT NULL,
	ACCG_UUID            VARCHAR(32) NOT NULL,
	UCAS_ACCOUNT         VARCHAR(18) NULL,
	MOBILE_ACCOUNT       VARCHAR(18) NULL,
	EMAIL_ACCOUNT        VARCHAR(35) NULL,
	PASSWORD             VARCHAR(35) NULL,
	FINGERPRINT          VARCHAR(255) NULL,
	SALT                 VARCHAR(18) NULL,
	CREATE_DATE          DATETIME NULL,
	MODIFY_DATE          DATETIME NULL,
	STATUS               CHAR(1) NULL
);



ALTER TABLE UCAS_USER_ACCOUNT
ADD PRIMARY KEY (ACC_UUID);



CREATE TABLE UCAS_USER_CLIENT_REL
(
	OPEN_ID              VARCHAR(32) NOT NULL,
	ACC_UUID             VARCHAR(32) NOT NULL,
	CLIENT_ID            VARCHAR(32) NOT NULL
);



ALTER TABLE UCAS_USER_CLIENT_REL
ADD PRIMARY KEY (OPEN_ID);



CREATE TABLE UCAS_USER_INFO
(
	ACC_UUID             VARCHAR(32) NOT NULL,
	REAL_NAME            VARCHAR(50) NULL,
	MOBILE_PHONE         VARCHAR(18) NULL,
	EMAIL                VARCHAR(35) NULL,
	SEX                  CHAR(1) NULL,
	HEAD_IMG_URL         VARCHAR(100) NULL,
	ORG_NAME             VARCHAR(100) NULL,
	CREATE_DATE          DATETIME NULL,
	MODIFY_DATE          DATETIME NULL
);



ALTER TABLE UCAS_USER_INFO
ADD PRIMARY KEY (ACC_UUID);



CREATE TABLE UCAS_USER_RES_REL
(
	UUID                 VARCHAR(32) NOT NULL,
	RES_UUID             VARCHAR(32) NOT NULL,
	OPEN_ID              VARCHAR(32) NOT NULL,
	SEL_FLAG             CHAR(1) NULL
);



ALTER TABLE UCAS_USER_RES_REL
ADD PRIMARY KEY (UUID);



alter TABLE UCAS_ACCCLI_GROUP_REL COMMENT = '应用组帐号组关系表' ;
    ALTER TABLE UCAS_ACCCLI_GROUP_REL CHANGE COLUMN UUID UUID VARCHAR(32) NOT NULL COMMENT 'UUID';
      ALTER TABLE UCAS_ACCCLI_GROUP_REL CHANGE COLUMN ACCG_UUID ACCG_UUID VARCHAR(32) NOT NULL COMMENT '帐号组UUID';
      ALTER TABLE UCAS_ACCCLI_GROUP_REL CHANGE COLUMN CLIG_UUID CLIG_UUID VARCHAR(32) NOT NULL COMMENT '应用组UUID';
      
alter TABLE UCAS_ACCOUNT_GROUP COMMENT = '帐号组参数表' ;
    ALTER TABLE UCAS_ACCOUNT_GROUP CHANGE COLUMN ACCG_UUID ACCG_UUID VARCHAR(32) NOT NULL COMMENT '帐号组UUID';
      ALTER TABLE UCAS_ACCOUNT_GROUP CHANGE COLUMN GROUP_NAME GROUP_NAME VARCHAR(50) NULL COMMENT '帐号组名称';
      ALTER TABLE UCAS_ACCOUNT_GROUP CHANGE COLUMN DESC_RIBE DESC_RIBE VARCHAR(200) NULL COMMENT '帐号组描述';
      
alter TABLE UCAS_CALL_TICKET COMMENT = '应用接口调用凭证表' ;
    ALTER TABLE UCAS_CALL_TICKET CHANGE COLUMN CALL_TICKE CALL_TICKE VARCHAR(32) NOT NULL COMMENT '调用凭证ticket';
      ALTER TABLE UCAS_CALL_TICKET CHANGE COLUMN CLIENT_ID CLIENT_ID VARCHAR(32) NOT NULL COMMENT '应用clientid';
      ALTER TABLE UCAS_CALL_TICKET CHANGE COLUMN RES_UUID RES_UUID TEXT NOT NULL COMMENT '资源UUID';
      ALTER TABLE UCAS_CALL_TICKET CHANGE COLUMN MAX_TIMES MAX_TIMES INTEGER NULL COMMENT '最大使用次数';
      ALTER TABLE UCAS_CALL_TICKET CHANGE COLUMN CUR_TIMES CUR_TIMES INTEGER NULL COMMENT '当前使用次数';
      ALTER TABLE UCAS_CALL_TICKET CHANGE COLUMN CREATE_DATE CREATE_DATE DATETIME NULL COMMENT '创建时间';
      ALTER TABLE UCAS_CALL_TICKET CHANGE COLUMN INVALID_DATE INVALID_DATE DATETIME NULL COMMENT '失效时间';
      ALTER TABLE UCAS_CALL_TICKET CHANGE COLUMN SCOPE SCOPE VARCHAR(2000) NULL COMMENT 'SCOPE';
      
alter TABLE UCAS_CLIENT_GROUP COMMENT = '应用组参数表' ;
    ALTER TABLE UCAS_CLIENT_GROUP CHANGE COLUMN CLIG_UUID CLIG_UUID VARCHAR(32) NOT NULL COMMENT '应用组UUID';
      ALTER TABLE UCAS_CLIENT_GROUP CHANGE COLUMN GROUP_NAME GROUP_NAME VARCHAR(50) NULL COMMENT '应用组名称';
      ALTER TABLE UCAS_CLIENT_GROUP CHANGE COLUMN DESC_RIBE DESC_RIBE VARCHAR(200) NULL COMMENT '应用组描述';
      ALTER TABLE UCAS_CLIENT_GROUP CHANGE COLUMN IS_SSO IS_SSO CHAR(1) NULL COMMENT '是否单点登录组';
      
alter TABLE UCAS_CLIENT_INFO COMMENT = '应用注册信息表' ;
    ALTER TABLE UCAS_CLIENT_INFO CHANGE COLUMN CLIENT_ID CLIENT_ID VARCHAR(32) NOT NULL COMMENT '应用clientid';
      ALTER TABLE UCAS_CLIENT_INFO CHANGE COLUMN CLIG_UUID CLIG_UUID VARCHAR(32) NOT NULL COMMENT '应用组UUID';
      ALTER TABLE UCAS_CLIENT_INFO CHANGE COLUMN CLIENT_SECRET CLIENT_SECRET VARCHAR(18) NULL COMMENT '应用口令';
      ALTER TABLE UCAS_CLIENT_INFO CHANGE COLUMN CLIENT_NAME CLIENT_NAME VARCHAR(100) NULL COMMENT '应用简称';
      ALTER TABLE UCAS_CLIENT_INFO CHANGE COLUMN DESC_RIBE DESC_RIBE VARCHAR(200) NULL COMMENT '应用描述';
      ALTER TABLE UCAS_CLIENT_INFO CHANGE COLUMN GRANT_TYPE GRANT_TYPE VARCHAR(100) NULL COMMENT '授权类型';
      ALTER TABLE UCAS_CLIENT_INFO CHANGE COLUMN CLIENT_URL CLIENT_URL VARCHAR(200) NULL COMMENT '应用主页';
      ALTER TABLE UCAS_CLIENT_INFO CHANGE COLUMN STATUS STATUS CHAR(1) NULL COMMENT '应用状态';
      ALTER TABLE UCAS_CLIENT_INFO CHANGE COLUMN CREATE_DATE CREATE_DATE DATETIME NULL COMMENT '创建时间';
      ALTER TABLE UCAS_CLIENT_INFO CHANGE COLUMN MODIFY_DATE MODIFY_DATE DATETIME NULL COMMENT '最近修改时间';
      
alter TABLE UCAS_CLIENT_RESGR_REL COMMENT = '应用授权资源组关系表' ;
    ALTER TABLE UCAS_CLIENT_RESGR_REL CHANGE COLUMN UUID UUID VARCHAR(32) NOT NULL COMMENT 'UUID';
      ALTER TABLE UCAS_CLIENT_RESGR_REL CHANGE COLUMN CLIENT_ID CLIENT_ID VARCHAR(32) NOT NULL COMMENT '应用clientid';
      ALTER TABLE UCAS_CLIENT_RESGR_REL CHANGE COLUMN RES_GROUP_UUID RES_GROUP_UUID VARCHAR(32) NOT NULL COMMENT '资源组UUID';
      ALTER TABLE UCAS_CLIENT_RESGR_REL CHANGE COLUMN MAX_TIMES MAX_TIMES INTEGER NULL COMMENT 'ticket使用次数';
      ALTER TABLE UCAS_CLIENT_RESGR_REL CHANGE COLUMN EXPIRY_DATE EXPIRY_DATE INTEGER NULL COMMENT 'ticket有效期';
      ALTER TABLE UCAS_CLIENT_RESGR_REL CHANGE COLUMN MODIFY_DATE MODIFY_DATE DATETIME NULL COMMENT '最近修改时间';
      ALTER TABLE UCAS_CLIENT_RESGR_REL CHANGE COLUMN CREATE_DATE CREATE_DATE DATETIME NULL COMMENT '创建时间';
      
alter TABLE UCAS_CLIENT_RESOURCE COMMENT = '应用资源表' ;
    ALTER TABLE UCAS_CLIENT_RESOURCE CHANGE COLUMN RES_UUID RES_UUID VARCHAR(32) NOT NULL COMMENT '资源UUID';
      ALTER TABLE UCAS_CLIENT_RESOURCE CHANGE COLUMN RES_GROUP_UUID RES_GROUP_UUID VARCHAR(32) NOT NULL COMMENT '资源组UUID';
      ALTER TABLE UCAS_CLIENT_RESOURCE CHANGE COLUMN RES_URI RES_URI VARCHAR(200) NULL COMMENT '资源URI';
      ALTER TABLE UCAS_CLIENT_RESOURCE CHANGE COLUMN DESC_RIBE DESC_RIBE VARCHAR(200) NULL COMMENT '资源描述';
      ALTER TABLE UCAS_CLIENT_RESOURCE CHANGE COLUMN IS_PRIVACY IS_PRIVACY CHAR(1) NULL COMMENT '是否涉及用户隐私';
      ALTER TABLE UCAS_CLIENT_RESOURCE CHANGE COLUMN IS_DEFAULT IS_DEFAULT CHAR(1) NULL COMMENT '是否资源组必须授权';
      ALTER TABLE UCAS_CLIENT_RESOURCE CHANGE COLUMN CREATE_DATE CREATE_DATE DATETIME NULL COMMENT '创建时间';
      ALTER TABLE UCAS_CLIENT_RESOURCE CHANGE COLUMN MODIFY_DATE MODIFY_DATE DATETIME NULL COMMENT '最近修改时间';
      ALTER TABLE UCAS_CLIENT_RESOURCE CHANGE COLUMN STATUS STATUS CHAR(1) NULL COMMENT '资源状态';
      
alter TABLE UCAS_CLIENT_TOKEN COMMENT = '应用令牌表' ;
    ALTER TABLE UCAS_CLIENT_TOKEN CHANGE COLUMN UUID UUID VARCHAR(32) NOT NULL COMMENT 'UUID';
      ALTER TABLE UCAS_CLIENT_TOKEN CHANGE COLUMN CLIENT_ID CLIENT_ID VARCHAR(32) NOT NULL COMMENT '应用clientid';
      ALTER TABLE UCAS_CLIENT_TOKEN CHANGE COLUMN OPEN_ID OPEN_ID VARCHAR(32) NOT NULL COMMENT 'OPENID';
      ALTER TABLE UCAS_CLIENT_TOKEN CHANGE COLUMN CODE CODE CHAR(18) NULL COMMENT '授权码';
      ALTER TABLE UCAS_CLIENT_TOKEN CHANGE COLUMN ACCESS_TOKEN ACCESS_TOKEN VARCHAR(32) NULL COMMENT '令牌token';
      ALTER TABLE UCAS_CLIENT_TOKEN CHANGE COLUMN MAX_TIMES MAX_TIMES INTEGER NULL COMMENT '最大使用次数';
      ALTER TABLE UCAS_CLIENT_TOKEN CHANGE COLUMN CUR_TIMES CUR_TIMES INTEGER NULL COMMENT '当前使用次数';
      ALTER TABLE UCAS_CLIENT_TOKEN CHANGE COLUMN CREATE_DATE CREATE_DATE DATETIME NULL COMMENT '创建时间';
      ALTER TABLE UCAS_CLIENT_TOKEN CHANGE COLUMN INVALID_DATE INVALID_DATE DATETIME NULL COMMENT '失效时间';
      ALTER TABLE UCAS_CLIENT_TOKEN CHANGE COLUMN REFRESH_TOKEN REFRESH_TOKEN VARCHAR(32) NULL COMMENT '刷新令牌';
      ALTER TABLE UCAS_CLIENT_TOKEN CHANGE COLUMN REFRESH_TOKEN_DATE REFRESH_TOKEN_DATE DATETIME NULL COMMENT '刷新令牌时效';
      ALTER TABLE UCAS_CLIENT_TOKEN CHANGE COLUMN SCOPE SCOPE VARCHAR(2000) NULL COMMENT 'SCOPE';
      
alter TABLE UCAS_RESOURCE_GROUP COMMENT = '资源组参数表' ;
    ALTER TABLE UCAS_RESOURCE_GROUP CHANGE COLUMN RES_GROUP_UUID RES_GROUP_UUID VARCHAR(32) NOT NULL COMMENT '资源组UUID';
      ALTER TABLE UCAS_RESOURCE_GROUP CHANGE COLUMN CLIENT_ID CLIENT_ID VARCHAR(32) NOT NULL COMMENT '应用clientid';
      ALTER TABLE UCAS_RESOURCE_GROUP CHANGE COLUMN GROUP_NAME GROUP_NAME VARCHAR(50) NULL COMMENT '资源组名称';
      ALTER TABLE UCAS_RESOURCE_GROUP CHANGE COLUMN DESC_RIBE DESC_RIBE VARCHAR(200) NULL COMMENT '资源组描述';
      
alter TABLE UCAS_TOKEN_STRATEGY COMMENT = '应用token策略表' ;
    ALTER TABLE UCAS_TOKEN_STRATEGY CHANGE COLUMN UUID UUID VARCHAR(32) NOT NULL COMMENT 'UUID';
      ALTER TABLE UCAS_TOKEN_STRATEGY CHANGE COLUMN CLIENT_ID CLIENT_ID VARCHAR(32) NOT NULL COMMENT '应用clientid';
      ALTER TABLE UCAS_TOKEN_STRATEGY CHANGE COLUMN MAX_TIMES MAX_TIMES INTEGER NULL COMMENT '最大使用次数';
      ALTER TABLE UCAS_TOKEN_STRATEGY CHANGE COLUMN EXPIRY_DATE EXPIRY_DATE INTEGER NOT NULL COMMENT 'Token有效期';
      ALTER TABLE UCAS_TOKEN_STRATEGY CHANGE COLUMN REFRESH_EXPIRY_DATE REFRESH_EXPIRY_DATE INTEGER NOT NULL COMMENT 'RefreshToken有效期';
      ALTER TABLE UCAS_TOKEN_STRATEGY CHANGE COLUMN STATUS STATUS CHAR(1) NOT NULL COMMENT '策略状态';
      ALTER TABLE UCAS_TOKEN_STRATEGY CHANGE COLUMN CREATE_DATE CREATE_DATE DATETIME NOT NULL COMMENT '创建时间';
      
alter TABLE UCAS_USER_ACCOUNT COMMENT = '用户认证信息表' ;
    ALTER TABLE UCAS_USER_ACCOUNT CHANGE COLUMN ACC_UUID ACC_UUID VARCHAR(32) NOT NULL COMMENT '帐号UUID';
      ALTER TABLE UCAS_USER_ACCOUNT CHANGE COLUMN ACCG_UUID ACCG_UUID VARCHAR(32) NOT NULL COMMENT '帐号组UUID';
      ALTER TABLE UCAS_USER_ACCOUNT CHANGE COLUMN UCAS_ACCOUNT UCAS_ACCOUNT VARCHAR(18) NULL COMMENT '网金帐号';
      ALTER TABLE UCAS_USER_ACCOUNT CHANGE COLUMN MOBILE_ACCOUNT MOBILE_ACCOUNT VARCHAR(18) NULL COMMENT '手机帐号';
      ALTER TABLE UCAS_USER_ACCOUNT CHANGE COLUMN EMAIL_ACCOUNT EMAIL_ACCOUNT VARCHAR(35) NULL COMMENT '邮箱帐号';
      ALTER TABLE UCAS_USER_ACCOUNT CHANGE COLUMN PASSWORD PASSWORD VARCHAR(35) NULL COMMENT '用户密码';
      ALTER TABLE UCAS_USER_ACCOUNT CHANGE COLUMN FINGERPRINT FINGERPRINT VARCHAR(255) NULL COMMENT '指纹标识';
      ALTER TABLE UCAS_USER_ACCOUNT CHANGE COLUMN SALT SALT VARCHAR(18) NULL COMMENT '随机盐';
      ALTER TABLE UCAS_USER_ACCOUNT CHANGE COLUMN CREATE_DATE CREATE_DATE DATETIME NULL COMMENT '创建时间';
      ALTER TABLE UCAS_USER_ACCOUNT CHANGE COLUMN MODIFY_DATE MODIFY_DATE DATETIME NULL COMMENT '最近修改时间';
      ALTER TABLE UCAS_USER_ACCOUNT CHANGE COLUMN STATUS STATUS CHAR(1) NULL COMMENT '帐号状态';
      
alter TABLE UCAS_USER_CLIENT_REL COMMENT = '用户应用授权表' ;
    ALTER TABLE UCAS_USER_CLIENT_REL CHANGE COLUMN OPEN_ID OPEN_ID VARCHAR(32) NOT NULL COMMENT 'OPENID';
      ALTER TABLE UCAS_USER_CLIENT_REL CHANGE COLUMN ACC_UUID ACC_UUID VARCHAR(32) NOT NULL COMMENT '帐号UUID';
      ALTER TABLE UCAS_USER_CLIENT_REL CHANGE COLUMN CLIENT_ID CLIENT_ID VARCHAR(32) NOT NULL COMMENT '应用clientid';
      
alter TABLE UCAS_USER_INFO COMMENT = '用户基本信息表' ;
    ALTER TABLE UCAS_USER_INFO CHANGE COLUMN ACC_UUID ACC_UUID VARCHAR(32) NOT NULL COMMENT '帐号UUID';
      ALTER TABLE UCAS_USER_INFO CHANGE COLUMN REAL_NAME REAL_NAME VARCHAR(50) NULL COMMENT '用户名称';
      ALTER TABLE UCAS_USER_INFO CHANGE COLUMN MOBILE_PHONE MOBILE_PHONE VARCHAR(18) NULL COMMENT '绑定手机';
      ALTER TABLE UCAS_USER_INFO CHANGE COLUMN EMAIL EMAIL VARCHAR(35) NULL COMMENT '绑定邮箱';
      ALTER TABLE UCAS_USER_INFO CHANGE COLUMN SEX SEX CHAR(1) NULL COMMENT '性别';
      ALTER TABLE UCAS_USER_INFO CHANGE COLUMN HEAD_IMG_URL HEAD_IMG_URL VARCHAR(100) NULL COMMENT '头像地址';
      ALTER TABLE UCAS_USER_INFO CHANGE COLUMN ORG_NAME ORG_NAME VARCHAR(100) NULL COMMENT '所属组织名称';
      ALTER TABLE UCAS_USER_INFO CHANGE COLUMN CREATE_DATE CREATE_DATE DATETIME NULL COMMENT '创建时间';
      ALTER TABLE UCAS_USER_INFO CHANGE COLUMN MODIFY_DATE MODIFY_DATE DATETIME NULL COMMENT '最近修改时间';
      
alter TABLE UCAS_USER_RES_REL COMMENT = '用户授权资源关系表' ;
    ALTER TABLE UCAS_USER_RES_REL CHANGE COLUMN UUID UUID VARCHAR(32) NOT NULL COMMENT 'UUID';
      ALTER TABLE UCAS_USER_RES_REL CHANGE COLUMN RES_UUID RES_UUID VARCHAR(32) NOT NULL COMMENT '资源UUID';
      ALTER TABLE UCAS_USER_RES_REL CHANGE COLUMN OPEN_ID OPEN_ID VARCHAR(32) NOT NULL COMMENT 'OPENID';
      ALTER TABLE UCAS_USER_RES_REL CHANGE COLUMN SEL_FLAG SEL_FLAG CHAR(1) NULL COMMENT '是否已选';
      





-- ----------------------------
-- Table structure for `manage_config`
-- ----------------------------
CREATE TABLE `manage_config` (
`id`  varchar(36) NOT NULL ,
`param_key`  varchar(50) NOT NULL ,
`param_value`  varchar(2000) NULL DEFAULT NULL ,
`param_desc`  varchar(200) NULL DEFAULT NULL ,
`status`  int(2) NULL DEFAULT NULL ,
PRIMARY KEY (`id`)
)

;

-- ----------------------------
-- Table structure for `manage_ip_schedule_task`
-- ----------------------------
CREATE TABLE `manage_ip_schedule_task` (
`id`  char(36) NOT NULL COMMENT 'id' ,
`task_code`  varchar(100) NOT NULL COMMENT '任务名称编码' ,
`task_name`  varchar(100) NOT NULL COMMENT '任务名' ,
`task_conf`  varchar(100) NOT NULL COMMENT '任务执行表达式' ,
`task_class`  varchar(100) NOT NULL COMMENT '任务执行类' ,
`task_server_ip`  varchar(100) NOT NULL COMMENT '任务执行的服务器' ,
`status`  char(1) NOT NULL DEFAULT '1' COMMENT '任务状态0:启用;1：禁用' ,
`remark`  varchar(250) NOT NULL COMMENT '备注' ,
PRIMARY KEY (`id`)
)
COMMENT='系统运行调度表'

;

-- ----------------------------
-- Table structure for `manage_log_info`
-- ----------------------------
CREATE TABLE `manage_log_info` (
`id`  varchar(36) NOT NULL ,
`create_time`  datetime NULL DEFAULT NULL ,
`ip_address`  varchar(16) NULL DEFAULT NULL ,
`log_level`  varchar(16) NULL DEFAULT NULL ,
`message`  varchar(256) NULL DEFAULT NULL ,
`user_name`  varchar(36) NULL DEFAULT NULL ,
`user_id`  varchar(36) NULL DEFAULT NULL ,
PRIMARY KEY (`id`)
)

;

-- ----------------------------
-- Table structure for `manage_module`
-- ----------------------------
CREATE TABLE `manage_module` (
`module_id`  varchar(36) NOT NULL ,
`description`  varchar(256) NULL DEFAULT NULL ,
`priority`  int(11) NULL DEFAULT NULL ,
`sn`  varchar(32) NULL DEFAULT NULL COMMENT '判断标志' ,
`url`  varchar(245) NULL DEFAULT NULL ,
`parent_id`  varchar(36) NULL DEFAULT NULL ,
`name`  varchar(64) NULL DEFAULT NULL ,
`leaf`  char(1) NULL DEFAULT '0' COMMENT '是否是叶子节点。0：不是叶子节点；1：是叶子节点' ,
`image` varchar(64) DEFAULT NULL,
PRIMARY KEY (`module_id`)
)

;

-- ----------------------------
-- Table structure for `manage_organization`
-- ----------------------------
CREATE TABLE `manage_organization` (
`org_id`  varchar(36) NOT NULL DEFAULT '' COMMENT '机构唯一标识' ,
`name`  varchar(64) NOT NULL COMMENT '名称' ,
`description`  varchar(256) NULL DEFAULT NULL COMMENT '描述' ,
`priority`  int(11) NULL DEFAULT NULL COMMENT '优先级' ,
`parent_id`  varchar(36) NULL DEFAULT NULL COMMENT '父机构id' ,
`root_id`  varchar(36) NULL DEFAULT NULL COMMENT '根机构id' ,
PRIMARY KEY (`org_id`)
)

;

-- ----------------------------
-- Table structure for `manage_permission`
-- ----------------------------
CREATE TABLE `manage_permission` (
`permission_id`  varchar(36) NOT NULL ,
`description`  varchar(256) NULL DEFAULT NULL COMMENT '描述' ,
`name`  varchar(64) NULL DEFAULT NULL COMMENT '名称' ,
`sn`  varchar(36) NULL DEFAULT NULL COMMENT '判断标识' ,
`module_id`  varchar(36) NULL DEFAULT NULL COMMENT '模块id' ,
`url_action`  varchar(256) NULL DEFAULT NULL COMMENT '资源URL' ,
PRIMARY KEY (`permission_id`)
)

;

-- ----------------------------
-- Table structure for `manage_role`
-- ----------------------------
CREATE TABLE `manage_role` (
`role_id`  varchar(36) NOT NULL COMMENT '角色唯一标识' ,
`description`  varchar(255) NULL DEFAULT NULL COMMENT '描述' ,
`name`  varchar(36) NULL DEFAULT NULL COMMENT '名称' ,
PRIMARY KEY (`role_id`)
)

;

-- ----------------------------
-- Table structure for `manage_role_module`
-- ----------------------------
CREATE TABLE `manage_role_module` (
`id`  varchar(36) NOT NULL ,
`module_id`  varchar(36) NOT NULL COMMENT '菜单Id' ,
`role_id`  varchar(36) NOT NULL COMMENT '角色id' ,
PRIMARY KEY (`id`)
)

;

-- ----------------------------
-- Table structure for `manage_role_param`
-- ----------------------------
CREATE TABLE `manage_role_param` (
`role_id`  varchar(36) NOT NULL DEFAULT '角色id' ,
`mark`  varchar(15) NOT NULL COMMENT '角色标志位' ,
PRIMARY KEY (`role_id`)
)
COMMENT='角色参数表'

;

-- ----------------------------
-- Table structure for `manage_role_permission`
-- ----------------------------
CREATE TABLE `manage_role_permission` (
`id`  varchar(36) NOT NULL ,
`permission_id`  varchar(36) NOT NULL COMMENT '权限Id' ,
`role_id`  varchar(36) NOT NULL COMMENT '角色id' ,
PRIMARY KEY (`id`)
)

;

-- ----------------------------
-- Table structure for `manage_serial_number`
-- ----------------------------
CREATE TABLE `manage_serial_number` (
`serial_number_id`  varchar(36) NOT NULL ,
`current_serial_number`  bigint(20) NULL DEFAULT NULL ,
`generated_serial_number`  bigint(20) NOT NULL ,
`serial_number_date`  date NOT NULL ,
PRIMARY KEY (`serial_number_id`)
)

;

-- ----------------------------
-- Table structure for `manage_user_account`
-- ----------------------------
CREATE TABLE `manage_user_account` (
`user_id`  varchar(36) NOT NULL ,
`create_time`  datetime NULL DEFAULT NULL COMMENT '创建时间' ,
`password`  varchar(64) NOT NULL COMMENT '密码' ,
`salt`  varchar(32) NOT NULL COMMENT '加密盐值' ,
`status`  tinyint(4) NULL DEFAULT 1 COMMENT '1:激活 ;  0:初始;  2：停用' ,
`account`  varchar(32) NOT NULL COMMENT '账号' ,
`email`  varchar(32) NULL DEFAULT NULL COMMENT '邮箱' ,
`mobilephone`  varchar(20) NULL DEFAULT NULL COMMENT '手机' ,
PRIMARY KEY (`user_id`)
)

;

-- ----------------------------
-- Table structure for `manage_user_organization`
-- ----------------------------
CREATE TABLE `manage_user_organization` (
`id`  varchar(36) NOT NULL ,
`user_id`  varchar(36) NOT NULL COMMENT '用户id' ,
`org_id`  varchar(36) NOT NULL COMMENT '机构id' ,
`root_org_id`  varchar(36) NULL DEFAULT NULL COMMENT '所属机构根节点id' ,
PRIMARY KEY (`id`)
)

;

-- ----------------------------
-- Table structure for `manage_user_profile`
-- ----------------------------
CREATE TABLE `manage_user_profile` (
`user_id`  varchar(36) NOT NULL ,
`name`  varchar(32) NULL DEFAULT NULL COMMENT '用户姓名' ,
`introduce`  varchar(255) NULL DEFAULT NULL COMMENT '个人介绍' ,
`telephone`  varchar(32) NULL DEFAULT NULL COMMENT '工作电话' ,
`mobilephone`  varchar(20) NULL DEFAULT NULL COMMENT '移动电话' ,
`create_date`  datetime NULL DEFAULT NULL COMMENT '创建时间' ,
`update_date`  datetime NULL DEFAULT NULL COMMENT '更新时间' ,
`email`  varchar(40) NULL DEFAULT NULL COMMENT '邮箱' ,
`birthday`  date NULL DEFAULT NULL COMMENT '生日' ,
`gender`  varchar(4) NULL DEFAULT '' COMMENT '性别' ,
`starff_id`  varchar(36) NULL DEFAULT NULL COMMENT '员工号' ,
`position`  varchar(36) NULL DEFAULT NULL COMMENT '职位' ,
`type`  varchar(255) NULL DEFAULT 'import' COMMENT '用户类型，import,ldap，register' ,
`isDelected`  char(1) NULL DEFAULT NULL COMMENT '0-正常 1-删除' ,
PRIMARY KEY (`user_id`)
)

;

-- ----------------------------
-- Table structure for `manage_user_role`
-- ----------------------------
CREATE TABLE `manage_user_role` (
`id`  varchar(36) NOT NULL ,
`role_id`  varchar(36) NOT NULL COMMENT '角色唯一标识' ,
`user_id`  varchar(36) NULL DEFAULT NULL ,
`priority`  int(4) NULL DEFAULT NULL ,
PRIMARY KEY (`id`)
)

;


CREATE TABLE `manage_user_oauth2_rel` (
  `uuid` varchar(32) NOT NULL COMMENT '资源UUID',
  `open_id` varchar(32) NOT NULL COMMENT '认证中心对应Openid',
  `user_id` varchar(36) NOT NULL COMMENT '账户ID',
  PRIMARY KEY (`uuid`)
) 
;