server:
  port: 8090
  context-path:
  session:
    timeout: 3600

spring:
  datasource:
    url: jdbc:mysql://172.17.22.38:8066/ucas_center
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      min-idle: 2
      max-idle: 10
      max-active: 20
      max-wait: 200
      test-on-borrow: true
  session:
      store-type: redis
  aop:
    auto: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/pages/
  redis:
     cluster:
          nodes:
            - 10.0.0.213:7080
            - 10.0.0.213:7081
            - 10.0.0.213:7082
            - 10.0.0.214:7083
            - 10.0.0.214:7084
            - 10.0.0.214:7085


  data:
    mongodb:
        uri: mongodb://admin:123456@172.17.22.38:7009,172.17.22.38:7010/client?replicaSet=repset&readPreference=primaryPreferred


#是否启动quartz任务扫描器
quartz:
  scan: false

mybatis:
  mapper-locations: classpath:sql/mapper/*.xml
